version: "3.9"

  python:
    container_name: python
    build:
      dockerfile: ./.devcontainer/Dockerfile.cdc_project
      context: ../
    volumes:
      - ../:/cdc_project/
    networks:
      - default
    tty: true
    environment:
      - POSTGRES_URI=postgresql://postgres:postgres@172.19.0.2:5432/data_pipeline?schema=public
      - ENVIRONMENT=local
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default: