version: "3.9"

services:
  python:
    container_name: python_cdc
    build:
      dockerfile: ./.devcontainer/Dockerfile.cdc_project
      context: ../
    volumes:
      - ../:/cdc_project/
    networks:
      - default
    tty: true
    environment:
      - POSTCODE=S6 2XF
      - STREET_NAME=Palm Street
      - HOUSE_NUMBER=57
      - CITY=Sheffield
      - WEBSITE_URL=https://wasteservices.sheffield.gov.uk
      - ENVIRONMENT=local
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default: